apiVersion: v1
kind: Namespace
metadata:
  name: app-namespace
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  namesapce: app-namespace
spec:
  replicas: 2
  selector:
    matchLabels:
      lab: app
  template:
    metadata: 
      labels:
        lab: app
    spec:
      containers:
        - name: app-con
          image: 
          ports:
            - containerPort: 8081
          env:
            - name: ASPNETCORE_URLS
              value: "http://*:8081"
            - name: ConnectionStrings__default
              value: "server=db-service.db-namespace.svc.cluster.local,1433;database=DotnetCoreMvcCrud;User Id=sa;Password=secure-Random-P@ss-11234;TrustServerCertificate=true;"
---
apiVersion: v1
kind: Service
metadata:
  name: app-service
  namespace: app-namespace
spec:
  selector:
    lab: app
type: NodePort
ports:
  - port: 8082
    targetPort: 8081 
    nodePort: 30001