apiVersion: v1
kind: Namespace
metadata:
  name: db-namesapce
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-pvc
  namesapce: db-namespace
spec: 
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: aws-class
  resources:
    requests:
      storage: 5Gi